# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.8", "3.9", "3.10"]

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: "pip"
            - name: Prepare
              run: |
                  sudo apt-get update
                  sudo apt-get install -y mesa-utils xvfb libgl1-mesa-dev
            - name: Test glxinfo
              run: |
                  sudo /usr/bin/Xvfb :0 -screen 0 1280x1024x24 &
                  glxinfo
            - name: Download Blender
              run: |
                  scripts/install_blender.sh
                  source .envs
            - name: Install Blender dependencies
              run: |
                  source .envs
                  blender --background --python scripts/install_btb.py
                  blender --background --python-use-system-env --python-expr "import blendtorch.btb as btb; print (btb.__version__)"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install flake8 pytest
                  python -m pip install -e pkg_pytorch
                  python -m pip install -r requirements_dev.txt
                  python -c "import blendtorch.btt as btt; print(btt.__version__)"
            - name: Lint with flake8
              run: |
                  # stop the build if there are Python syntax errors or undefined names
                  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                  # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                  flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
            - name: Test with pytest
              run: |
                  source .envs
                  pytest tests -m background
